name: MultiTeamManhunt
version: 1.1.0
author: TheSteak
main: me.TheSteak.multiteammanhunt.Main
description: A plugin that allows for tracking of different players on the speedrunner team

commands:
  manhuntcompass:
    aliases: [mhc]
    description: /mhc to give self a compass
  teamhunter:
    aliases: [thunt]
    description: /thunt to set team as hunter
  teamrunner:
    aliases: [trun]
    description: /trun to set team as runner
  switchtrack:
    aliases: [switch]
    description: /switch as hunter to switch who is being tracked
  startcompass:
    aliases: [startcp]
    description: /startcp to start updating the hunters compasses
  stopcompass:
    aliases: [stopcp]
    description: /stopcp to stop updating the hunters compasses
    